name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # 主分支名称，根据实际情况修改

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm" # 或 'pnpm'

      - name: Install dependencies
        run: npm install
        # 或 pnpm install

      - name: Build
        run: npm run build
        # 或 pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
